project:
  type: website
  output-dir: docs

website:
  title: "Hibah Ganie"
  favicon: pics/logo.png
  navbar:
    title: false # override printing webiste title  in navbar
    logo: pics/logo.png
    logo-alt: "Hibah's Logo"
    left: 
      - href: index.qmd
        text: Home
      - href: mywork.qmd
        text: What Im Watching
      - href: project.qmd
        text: My Project
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: styles.scss
    mainfont: Rubik
    toc: true
    page-layout: full


