project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Hibah Ganie"
    left: 
      - href: index.qmd
        text: Home
      - href: mywork.qmd
        text: My Work
      - href: project.qmd
        text: My Project
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

